tried separate view from logic; splitted store to two context;
iamr0man/prjctr pull request #4
Opened 2022-02-03 12:44 UTC by iamr0man

2022-02-03 15:27 UTC, Rastopyr requested changes

2022-02-03 15:27 UTC, Rastopyr commented on src/components/CreateNote/ContentInput/index.js
> +        if (!editor) return;
editor используется раньше чем объявлен. ошибка в рантайме может быть

2022-02-03 15:27 UTC, Rastopyr commented on src/components/CreateNote/ContentInput/index.js
> +        const txt = document.createElement("textarea");
Выглядит как очень странный хак) Расскажешь зачем так декодировать html?

2022-02-03 15:27 UTC, Rastopyr commented on src/components/CreateNote/ContentInput/index.js
> +        const txt = document.createElement("textarea");
Этот метод можно вынести за пределы компонента, он не зависит от скоупа.

2022-02-03 15:27 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/CreateNoteFormView.js
> +                    rules={[
Мне кажется что эти правила валидации никак не учитываются при обработке значений формы.

2022-02-03 15:27 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/CreateNoteFormView.js
> +                    rules={[
То есть я могу сделать submit с невалидным контентом

2022-02-03 15:27 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/index.js
> +    const [isHtmlPasted, setPastedFlag] = useState(false)
Судя по diff это поле больше нигде не используется

2022-02-03 15:27 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/index.js
> +    const [state, action] = useNoteState()
`action` -> `actions`

2022-02-03 15:27 UTC, Rastopyr commented on src/components/NoteDisplaying/index.js
> +        const noteDisplaying = document.getElementsByClassName('note-displaying')
Прямой работы с DOM быть не должно, попробуй переписать явно через стейт.

2022-02-03 15:27 UTC, Rastopyr commented on src/components/NoteDisplaying/index.js
>              [...node.children].forEach(v => iterateTroughNoteAndAddEventToLink(v))
Для чего используется этот метод? Там происходит прямая работа с DOM, этого нужно избежать. Попробуй переписать на более честный react-way

2022-02-03 15:27 UTC, Rastopyr commented on src/components/NoteList/NoteItem/index.js
> +            getHandledText={getHandledText}
openNoteDetails -> onOpenNote
editNoteDetails -> onEditNote
deleteNoteFromList -> onDeleteNode

Контракт компонента должен отражать что он делает. В данном случае компонент сообщает родительскому компоненту про события внутри.

openNoteDetails и остальные имена проспов звучат очень императивно, и использовать такой компонент, не зная про то как он работает - сложно.

2022-02-03 15:27 UTC, Rastopyr commented on src/components/NoteList/index.js
> +        openCreateNoteForm={openCreateNoteForm}
снова императивное название пропса

2022-02-03 15:27 UTC, Rastopyr commented on src/components/NoteList/index.js
> +        filterValue={filterValue}
мне кажется что вместо filterValue должно быть `onsSearchChange` и передаваться только searchedValue

2022-02-03 15:27 UTC, Rastopyr commented on src/components/NoteList/index.js
> +                        if (filterValue(item, searchedValue)) {
Логика фильтрации должна находится компонентом выше. Это просто вьюшка, которая про поиск ничего не знает. Просто сообщает на верх об изменении поискового запроса.

Представь что завтра для поиска нужно будет использовать network request, эта логика быстро сломается

2022-02-03 15:27 UTC, Rastopyr commented on src/components/NoteList/index.js
> +function NoteListView ({ noteList, openCreateNoteForm, filterValue }) {
Плюс контракт компонента не отражает то что компонент делает. Без знания имплементации этого компонента, пользоваться им будет сложно

2022-02-03 15:27 UTC, Rastopyr commented on src/store/actions/index.js
>          const data = localStorage.getItem(NOTE_LIST)
Я писал уже в issues, стоит убрать работу c localStorage из action-creator

2022-02-03 15:27 UTC, Rastopyr commented on src/store/modules/FormState.js
> +        toggleCreateForm: toggleCreateForm(dispatch)
Что делает toggleCreateForm? Между какими состояниям происходит переключение? Может стоит сделать на переключение в каждое состояние явный переключатель?

2022-02-03 15:27 UTC, Rastopyr commented on src/store/modules/NoteState.js
> +        selectNote: selectNote(dispatch),
selectNote как работа с формой, на мой взгляд, это ответственность другого контекста

2022-02-03 15:27 UTC, Rastopyr commented on src/store/reducers/index.js
> +export const formListReducer = (state, event) => {
Два редьюсера в одном файле - сложно читать и поддерживать. Стоит разделять логику по файлам относительно домена.

`note`-domain - отдельно
`form`-domain - отдельно
и тд

2022-02-03 15:27 UTC, Rastopyr commented on src/components/Main/index.js
> +        // <FormProvider>
Забыл убрать коммент?

2022-02-03 15:27 UTC, Rastopyr commented on src/components/Main/index.js
> +export const FormProvider = ({ children }) => {
В этом файле много всего находится. Давай разобъем на несколько изолированных модулей.

2022-02-03 15:27 UTC, Rastopyr commented on src/components/Main/index.js
> +        <NoteListContext.Provider value={[state, dispatch]}>
`FormProvider` использует `NoteListContext`. Так делать нельзя, иначе один из контекстов перетрет значение другого.

С точки зрения системы типов это ошибка компиляции

2022-02-04 06:57 UTC, iamr0man commented on src/components/CreateNote/ContentInput/index.js
> +        const txt = document.createElement("textarea");
html разметку вревращает в текст - убирает теги, аттриуты и тд. но вроде не для всех элементов

2022-02-04 07:04 UTC, iamr0man commented on src/components/CreateNote/CreateNoteForm/CreateNoteFormView.js
> +                    rules={[
правила формы учитываются, если тайтл пустой или имеет больше 15 символов - заметка не создается

2022-02-04 07:42 UTC, iamr0man commented on src/store/modules/FormState.js
> +        toggleCreateForm: toggleCreateForm(dispatch)
 не boolean значение, а тестовое значение (тип отображения) ?

2022-02-08 12:36 UTC, Rastopyr commented on src/components/CreateNote/ContentInput/index.js
> +        const txt = document.createElement("textarea");
Ну по идее, если юзер написал текст и как то его отформатировал, то это форматирование нужно сохранить.

2022-02-08 12:36 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/CreateNoteFormView.js
> +                    rules={[
@iamr0man ты имеешь в виду что не сабмитится форма?

2022-02-08 12:37 UTC, Rastopyr commented
Спасибо за разбиение по коммитам! Так намного удобнее ревьюить!

2022-02-08 12:39 UTC, iamr0man commented on src/components/CreateNote/CreateNoteForm/CreateNoteFormView.js
> +                    rules={[
да, кнопку нажать можно, но он добавит красное выделение текста и не запушит в массив с заметками

2022-02-08 12:41 UTC, iamr0man commented on src/components/CreateNote/ContentInput/index.js
> +        const txt = document.createElement("textarea");
имел ввиду, что он для глаз убирает теги и само форматирование сохраняется

2022-02-08 12:54 UTC, Rastopyr requested changes

2022-02-08 12:54 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/index.js
>      const [title, setTitle] = useState('')
С точки зрения логики, эти данные должны находится внутри form. Это его отвественность.

2022-02-08 12:54 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/index.js
>      const [title, setTitle] = useState('')
`title` и `content`

2022-02-08 12:54 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/index.js
>          form.resetFields();
Если `title` и `content` должны ресетится один раз. Если они будут хранится в одном месте(form context) то ли дублирование данных уйдет и ддублирование операций.

2022-02-08 12:54 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/CreateNoteFormView.js
> +                    rules={[
Это нельзя потестировать без использования react-lifecycle, а следовательно быстро менять или следовательно масштабировать. Логика спрятана внутри view слоя, и что еще сложнее, в третьей зависимости. Давай правила валидации и создание ошибок вынесем в form context.

Суть такого изменения, чтобы более явно провести между слоями границы. Бизнес логика(валидация) отдельно, а представление - отдельно.

2022-02-08 13:08 UTC, Rastopyr requested changes

2022-02-08 13:08 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/index.js
> +            actions.createNote({ id: new Date().getTime(), title, content })
Хм, а это я предложил сюда перенести генерацию id? Для создания заметки это лучше оставить внутри модельки, и лучше использовать какой нибудь `uuid` пакет, но это опционально.

2022-02-08 13:08 UTC, Rastopyr commented on src/constants.js
> +export const VIEW = 'VIEW'
VIEW_FORM_MODE

2022-02-08 13:08 UTC, Rastopyr commented on src/constants.js
> +export const CREATE = 'CREATE'
CREATE_FORM_MODE

2022-02-08 13:08 UTC, Rastopyr commented on src/constants.js
> +export const VIEW = 'VIEW'
Сейчас эти контстанты не отражают, какой в них закладывался автором смысл. Стоит сделать более конкретным их описание.

2022-02-08 13:09 UTC, Rastopyr commented on src/App.js
> +        actions.initNoteList(data)
Nice work!

2022-02-08 13:10 UTC, Rastopyr requested changes

2022-02-08 13:10 UTC, Rastopyr commented on src/store/actions/index.js
>      try {
dispatch не должен вызывать исключение

2022-02-09 14:21 UTC, Rastopyr commented on src/components/CreateNote/CreateNoteForm/index.js
>          form.resetFields();
Ты имеешь в виду dispatch/чтение данных? Ну если это будет проблемой для производительности то такой подход надо оптимизировать но это уже отдельная задача.

2022-02-10 18:05 UTC, Rastopyr requested changes

2022-02-13 09:44 UTC, Rastopyr approved these changes

2022-02-14 11:02 UTC, merged